pkg/katapult/api_client.go, pkg/katapult/api_client_test.go
This means less checking for nil, or missing to check for nil in some cases.
=> fix(client): ensure apiClient.Do() never returns a nil \*Response

pkg/katapult/api_client.go, pkg/katapult/api_client_test.go, pkg/katapult/client_test.go, pkg/katapult/organization_test.go, pkg/katapult/virtual_machine_build_test.go
Exposes error details as a pretty printed JSON string at the end of error types.
This is a temporary stop-gap before creating unique types for each error that
can happen, which formats the details into text as relevant for each error type.
=> feat(errors): simple method of including error details as a formatted JSON string

pkg/katapult/data_center.go, pkg/katapult/data_center_test.go, pkg/katapult/disk_template.go, pkg/katapult/disk_template_test.go, pkg/katapult/dns_zone.go, pkg/katapult/dns_zone_test.go, pkg/katapult/field_name.go, pkg/katapult/ip_address.go, pkg/katapult/ip_address_test.go, pkg/katapult/network.go, pkg/katapult/network_test.go, pkg/katapult/organization.go, pkg/katapult/organization_test.go, pkg/katapult/trash_object.go, pkg/katapult/trash_object_test.go, pkg/katapult/virtual_machine.go, pkg/katapult/virtual_machine_package.go, pkg/katapult/virtual_machine_package_test.go, pkg/katapult/virtual_machine_test.go, pkg/katapult/zone.go, pkg/katapult/zone_test.go
For resource types which can be looked up / queried based on multiple fields,
these new functions allows creating a shallow struct which just contains the
relevant lookup field.
Most methods which accept resources as input, like the
`Create(context.Context, *Organization, *IPAddressCreateArguments)` function on
the `IPAddressesClient`, only uses the `*Organization` to figure out which
organization to create the IP within. This means it does not need to be a
complete `*Organization` with all fields populated, but instead it can be a
shallow struct containing only a `ID` or `SubDomain` value.
The `NewOrganizationLookup()` function accepts a string that can either be a
organization ID (formatted as `org_<random>`), or a organization sub-domain
(formatted as a DNS Label). Based on the format …
=> feat(katapult): add New<resource>Lookup() functions

pkg/katapult/client.go, pkg/katapult/client_test.go
We already have a HTTPClient configuration option, to provide a custom
http.Client instance to preform all HTTP requests. The Transport option was
hastily added for testing purposes, but tests should really have used the
HTTPClient option from the beginning.
This was especially problematic if you provided both options, as the transport
of the custom http.Client would be replaced with the provided Transport.
BREAKING CHANGE: Remove Transport configuration option. Use existing HTTPClient
option instead.
=> fix(config)!: remove Transport configuration option

pkg/katapult/ip_address.go, pkg/katapult/ip_address_test.go
A version argument of type IPVersion is required when creating an IP address, so
it makes sense to be able to read the version value back out from existing IP
address records. The API does not expose that however, so we simply detect it by
parsing the Address string.
=> feat(ip_address): add (*IPAddress).Version() function

pkg/katapult/client.go, pkg/katapult/fixtures/organization_not_activated_error.json, pkg/katapult/fixtures/virtual_machine_groups_list.json, pkg/katapult/organization_test.go, pkg/katapult/virtual_machine.go, pkg/katapult/virtual_machine_group.go, pkg/katapult/virtual_machine_group_test.go, pkg/katapult/virtual_machine_test.go
Adds the [List virtual machine groups](https://developers.katapult.io/api/docs/latest/routes/organizations/:organization/virtual_machine_groups/get/) endpoint to the Katapult client.
=> feat(virtual_machine_groups): add List endpoint

core/load_balancer.go, core/load_balancer_test.go, core/testdata/TestLoadBalancerCreateArguments_JSONMarshaling/false_HTTPSRedirect.golden, core/testdata/TestLoadBalancerUpdateArguments_JSONMarshaling/false_HTTPSRedirect.golden
Trying to update load balancers to set the HTTPS Redirect property to false was
not possible, as a false value would cause the field to not be included in the
marshaled JSON payload, which the API interprets as "no change".
Hence the field type needs to be `*bool` so we can distinguish between `true`,
`false`, and nil/missing.
=> fix(load_balancer): disable https_redirect

core/data_center.go, core/data_center_test.go
This returns the default network for a given data center.
This is needed by the Terraform provider for example. Currently it does a very
optimistic lookup by listing all networks for a data center and picking the
first network which has the word "public" in its name.
I'm not a fan of having to mess with the `doRequest` method and introducing a
new `request` method, but #99 should improve this situation when it's
implemented.
=> feat(data_center): add DefaultNetwork method

core/load_balancer_rule.go, core/load_balancer_rule_test.go, core/testdata/TestLoadBalancerRuleArguments_JSONMarshalling/remove_all_certificates.golden
Previously when setting the Certificates field to a empty slice, the field would
not be sent. This prevented making a request to remove all certificates assigned
to a rule. Hence we need to make the Certificates field a slice pointer, so we
can differentiate between not provided (no change), and empty list (remove all).
=> fix(load_balancer): enable removing all certs from a rule

core/client_test.go, core/load_balancer_rule_test.go, core/security_group_rule_test.go
Previously we were not actually testing the manipulation of the
katapult.Response object that paginated list endpoints perform. As the
pagination data comes from parsing the main response body, it must be manually
assigned to the katapult.Response object within the List() function.
This assignment could be completely removed and the existing tests we had in
place would happily carry on working. Now the response that the testclient
returns, and the wanted/expected response are two separate things, allowing us
to validate that the List() function is actually populating the the Pagination
field on the Response object.
=> test(testclient): improve usage of testclient in tests

errors.go, tools/codegen/gen/errors.go
The underlying project that Katapult for it's API was renamed from Rapid to Apia
(and open-sourced). This changed some internal naming conventions in the schema
file produced by Katapult's API, which in turn broke codgen here in go-katapult,
due to the basic types living within the "Apia" top-level namespace instead of
"Rapid" as they used to.
This change makes codegen compatible with both old and new schema formats.
=> fix(codegen): fix issue caused by a recent change to Katapult's API Schema

.github/workflows/ci.yml
We don't really use them, as we've only got benchmarks in the namegenerator
package. And as of late, they're unreliable and fluctuate.
=> ci(github): remove benchmark CI tasks

core/security_group_rule.go, core/security_group_rule_test.go, core/testdata/TestSecurityGroupRuleRef_JSONMarshaling/full.golden, core/testdata/TestSecurityGroupRule_JSONMarshalling/full.golden
Without this, it was not possible to determine what Security Group a
rule belonged to when fetching a Rule by its ID.
=> feat(core/SecurityGroupRule): add SecurityGroup ref field

core/load_balancer_rule.go, core/load_balancer_rule_test.go, core/security_group_rule.go, core/security_group_rule_test.go
They previously returned a slice of concrete types rather than a slice of
pointer types like all other List() methods we have. Hence this is worth it for
the sake of consistency, despite it being a breaking change.
=> fix(core): change return type of List() method on SecurityGroupRules and LoadBalancerRules

Makefile, core/client_test.go, core/errors_generated.go, internal/test/marshalling.go, schemas/core/v1.json, tools/schemafetcher/main.go
It also makes a few minor changes to the schemafetcher helper tool, primarily adding a feature to override the Base URL where the schemas are fetched from.
This is required to update the schema based on dev or staging environments for PR's which depend on schema changes not yet deployed to production.
=> chore(schemas): update core/v1 schema and update generated errors

.golangci.yml, buildspec/buildspec_test.go, core/load_balancer_rule.go, core/load_balancer_rule_test.go, core/testdata/TestLoadBalancerRuleArguments_JSONMarshalling/full.golden, katapult_test.go
Included in this PR: 
* Introduces `BackendSSL` and `PassthroughSSL` to the `LoadBalancerRuleArguments` type.
* Removal of `depguard` linter
* `_` of remaining `unused` params highlighted by lint warnings.
=> feat(load-balancer-rule): add backend + passthrough SSL

core/virtual_machine.go, core/virtual_machine_test.go
This add constants for two new possible VM states which each VM briefly
transitions through during start up.
=> feat(core/virtual-machine): add new "allocating" and "allocated" states

.github/workflows/nightly.yml
The `1.20` integer value was being interpreted as Go 1.2.x, not 1.20.x.
=> ci(nightly): fix go version so workflow works

go.mod, go.sum, next/Dockerfile, next/core/core.go, next/oapi-codegen-config.yml, next/public/public.go
Uses https://github.com/oapi-codegen/nullable
https://github.com/oapi-codegen/oapi-codegen#generating-nullable-types
We should have a nicer interface for working with nullable responses.
=> feat(next): add nullable output option to generator

next/client.go, next/core/core.go, next/generate.sh, next/katapult-core-openapi.json, next/katapult-public-openapi.json
Also update the generate.sh script to print some basic information about what it is doing.
=> feat(next): update generated core and public clients from Katapult 2.68.0 schemas
